-- FUNCIONES
--FUNCIONES DE CADENA DE TEXTO
USE pcventas
--LEFT - IZQUIERDA 
--OBTENER CARACTER DESDE LA IZQUIERDA
SELECT *,LEFT(NOMCLIENTE,6) FROM CLIENTES
--RIGHT-  DERECHA
--OBTENER CARACTER DESDE LA DERECHA
SELECT *,RIGHT(NOMCLIENTE,6) FROM CLIENTES
-- LEN
--OBTENER LA CANTIDAD TOTAL DE CARACTERES
SELECT *,LEN(NOMCLIENTE) FROM CLIENTES
--CHARINDEX - HALLAR 
--DEVUELVE LA POSICION DE UN CARACTER HALLADO
SELECT *, CHARINDEX('A',NOMCLIENTE,2) FROM CLIENTES
--SUBSTRING - EXTRAE
--EXTRAE 1 O MÁS DESDE UNA POSICION INICIAL
SELECT * , SUBSTRING(NOMCLIENTE,2,3) FROM Clientes
--

