--UNION DE FUNCIONES
USE pcventas
--SEPARAR LOS DATOS DE NOMCLIENTE DE LA TABLA CLIENTES
SELECT LEFT(NOMCLIENTE,CHARINDEX(' ',NOMCLIENTE)),* FROM Clientes

--
SELECT IIF(CHARINDEX(' ',NOMCLIENTE)=0,NOMCLIENTE,
LEFT(NOMCLIENTE,CHARINDEX(' ',NOMCLIENTE,1)  )
) AS NOMBRE,*
FROM Clientes
-----------------------------
SELECT IIF(CHARINDEX(' ',NOMCLIENTE)=0,NOMCLIENTE,
LEFT(NOMCLIENTE,CHARINDEX(' ',NOMCLIENTE,1)  )
) AS NOMBRE,
IIF(CHARINDEX(' ',NOMCLIENTE)=0,'',
 SUBSTRING(NOMCLIENTE,
 CHARINDEX(' ',NOMCLIENTE)+1,
 LEN(NOMCLIENTE) - CHARINDEX(' ',NOMCLIENTE,1))) AS NOMBRE_2

FROM Clientes
---VISTA
CREATE VIEW V_CLIENTES_NOMBRES
AS
SELECT IIF(CHARINDEX(' ',NOMCLIENTE)=0,NOMCLIENTE,
LEFT(NOMCLIENTE,CHARINDEX(' ',NOMCLIENTE,1)  )
) AS NOMBRE,
IIF(CHARINDEX(' ',NOMCLIENTE)=0,'',
 SUBSTRING(NOMCLIENTE,
 CHARINDEX(' ',NOMCLIENTE)+1,
 LEN(NOMCLIENTE) - CHARINDEX(' ',NOMCLIENTE,1))) AS NOMBRE_2

FROM Clientes
--
SELECT LEFT(nOMBRE_2,CHARINDEX(' ',nOMBRE_2))
FROM V_CLIENTES_NOMBRES
--------------------CONSULTA COMPLETA
SELECT IIF(CHARINDEX(' ',NOMCLIENTE)=0,NOMCLIENTE,
LEFT(NOMCLIENTE,CHARINDEX(' ',NOMCLIENTE,1)  )
) AS NOMBRE,
IIF(CHARINDEX(' ',NOMCLIENTE)=0,'',
 SUBSTRING(NOMCLIENTE,
 CHARINDEX(' ',NOMCLIENTE)+1,
 LEN(NOMCLIENTE) - CHARINDEX(' ',NOMCLIENTE,1))) AS NOMBRE_2,
  IIF(CHARINDEX(' ',NomCliente,CHARINDEX(' ',NOMCLIENTE)+1)>0,
SUBSTRING(NOMCLIENTE,CHARINDEX(' ',NomCliente,CHARINDEX(' ',NOMCLIENTE)+1),50),'')
AS NOMBRE_3
FROM Clientes

---
SELECT	*
		, IIF(CHARINDEX(' ', NomCliente) = 0, TRIM(NomCliente),
		LEFT(TRIM(NomCliente), CHARINDEX(' ', TRIM(NomCliente))-1)) AS NOMBRE,
		--APELLIDO
		IIF(CHARINDEX(' ', TRIM(NomCliente)) = 0, ' ',

		SUBSTRING(TRIM(NomCliente),(CHARINDEX(' ', TRIM(NomCliente)))+1,CHARINDEX(' ', SUBSTRING(TRIM(NomCliente),(CHARINDEX(' ', TRIM(NomCliente)))+1,LEN(TRIM(NomCliente)))))) AS APELLIDO,

		IIF(CHARINDEX(' ', SUBSTRING(TRIM(NomCliente),(CHARINDEX(' ', TRIM(NomCliente)))+1,LEN(TRIM(NomCliente)))) = 0, ' ',

		SUBSTRING(TRIM(SUBSTRING(TRIM(NomCliente),(CHARINDEX(' ', TRIM(SUBSTRING(TRIM(NomCliente),(CHARINDEX(' ', TRIM(NomCliente)))+1,LEN(TRIM(NomCliente))))))+1,LEN(TRIM(NomCliente)))),(CHARINDEX(' ', TRIM(NomCliente)))+1,LEN(TRIM(NomCliente)))) AS APELLIDO2
FROM Clientes

		