USE ejercicio_1
GO
-- COMANDOS DML LENGUAJE DE MANIPULACIÓN
-- DE DATOS
SELECT *
FROM LABORATORIO
--INSERTAR REGISTROS
INSERT INTO LABORATORIO(UBICACION)
VALUES('PRIMER PISO')
INSERT INTO LABORATORIO(UBICACION)
VALUES('SEGUNDO PISO')
INSERT INTO LABORATORIO(UBICACION)
VALUES('TERCER PISO')