--COMANDOS DDL LENGUAJE DE DEFINICIÓN DE DATOS
create database ejercicio_1
GO
USE EJERCICIO_1
GO
--CREAR TABLA
CREATE TABLE LABORATORIO(
COD_LABORATORIO INT PRIMARY KEY IDENTITY,
UBICACION VARCHAR(100)
)
--ELIMINAR UNA TABLA
--DROP TABLE LABORATORIO
--
--MODIFICAR UNA TABLA
--AGREGAR UNA COLUMNA A UNA TABLA
ALTER TABLE LABORATORIO
ADD FECHA_CREACION DATE
--AGREGAR UNA COLUMNA A UNA TABLA
--FUNCIONA SOLO PARA NUEVOS REGISTROS
ALTER TABLE LABORATORIO
ADD  ESTADO2 CHAR(1) DEFAULT '1'
--ELIMINAR UNA RESTRICCION DE UNA TABLA
ALTER TABLE LABORATORIO 
DROP CONSTRAINT DF__LABORATOR__ESTAD__276EDEB3
--ELIMINAMOS LA COLUMNA
ALTER TABLE LABORATORIO 
DROP COLUMN ESTADO2
--RENOMBRAR UNA TABLA
EXEC sp_rename 'LABORATORIO','LABORATORIOS' 

----------------------------------------------
-- CREAR UNA TABLA RELACIONADA - DEPENDIENTE
CREATE TABLE COMPUTADORA(
COD_COMPUTADORA INT PRIMARY KEY IDENTITY,
COD_LABORATORIO INT,
FOREIGN KEY (COD_LABORATORIO) 
REFERENCES LABORATORIO(COD_LABORATORIO),
COMPONENTES VARCHAR(100),
DESCRIPCION VARCHAR(50)
)
GO

