CREATE DATABASE EJERCICIO_2
GO
USE EJERCICIO_2

CREATE TABLE ESPECIES (
COD_ESPECIE INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR (255),
DESCRIPCION VARCHAR(255)
)

CREATE TABLE POKEMONES (
COD_POKEMON INT PRIMARY KEY IDENTITY,
COD_ESPECIE INT, 
FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIES (COD_ESPECIE),
NOMBRE VARCHAR (255),
FECHA_NACIMIENTO DATE,
TAMANO VARCHAR (255),
CANTIDAD_EVOLUCIONES NUMERIC (10)
)

INSERT INTO ESPECIES (
NOMBRE, DESCRIPCION) VALUES ('TIERRA','')
INSERT INTO ESPECIES (
NOMBRE, DESCRIPCION) VALUES ('AGUA','')

INSERT INTO POKEMONES (
COD_ESPECIE,NOMBRE,FECHA_NACIMIENTO,TAMANO,CANTIDAD_EVOLUCIONES) 
VALUES (1,'DIGLET','08-25-2023','',1)

INSERT INTO POKEMONES (
COD_ESPECIE,NOMBRE,FECHA_NACIMIENTO,TAMANO,CANTIDAD_EVOLUCIONES) 
VALUES (2,'SQUARTLE','07-31-2023','',2)

SELECT * FROM ESPECIES
SELECT * FROM POKEMONES