USE PCVENTAS_2
SELECT * FROM Categorias
GO
/*CREAR UN TRIGGER PARA NO REPETIR EL MISMO VALOR
*/
INSERT INTO Categorias(Nombre)VALUES('MULtimedias1')
GO
ALTER TRIGGER TX_CATEGORIAS_VALIDAR ON CATEGORIAS
	FOR INSERT
AS
	BEGIN
	

DECLARE @NOMBRE VARCHAR(40)=(SELECT NOMBRE FROM inserted)

	IF (SELECT count(*) FROM inserted, Categorias WHERE 
	INSERTED.NOMBRE =Categorias.Nombre) > 1 
	BEGIN
	PRINT 'YA EXISTE ESTE NOMBRE DE CATEGORIA'
		ROLLBACK TRANSACTION
	
	END
		ELSE
	BEGIN
	PRINT 'INSERTADO CORRECTAMENTE'	
	END
END

