--DISPARADORES
--TRIGGERS
--ES UN PROCEDIMIENTO QUE ACTUA CUANDO
--SE EJECUTA UN COMANDO DML
-------INSERT - UPDATE - DELETE
USE PCVENTAS_2
SELECT * FROM Categorias
INSERT INTO Categorias(Nombre)
VALUES ('PANTALONES')
GO
--
CREATE TRIGGER TX_MENSAJE_CLIENTE
ON CLIENTES
	FOR INSERT,UPDATE
AS
	PRINT 'INSERCIÓN O ACTULIZACION DE LA TABLA CLIENTES'
GO
--
SELECT * FROM CLIENTES
INSERT INTO Clientes(Idcliente,NomCliente,DirCliente,
TelCliente,Email)
VALUES('C0260','ANTHONY','','','')
GO
--
--DESHABILITAR TRIGGER
DISABLE TRIGGER TX_MENSAJE_CLIENTE ON CLIENTES
GO
--HABILITAR TRIGGER
ENABLE TRIGGER TX_MENSAJE_CLIENTE ON CLIENTES
GO
DROP TRIGGER TX_MENSAJE_CLIENTE
GO
--modificar
alter trigger TX_MENSAJE_CLIENTE ON CLIENTES
	FOR INSERT, UPDATE
AS 
BEGIN
	PRINT 'INSERCIÓN O ACTULIZACION DE LA TABLA CLIENTES 3'
END
---

--
SELECT * FROM Detalles
SELECT * FROM Articulos
--
INSERT INTO Detalles(IdFactura,IdArticulo,PreVenta,Cantidad)
VALUES(10000,'A0001',25,10)
GO
CREATE TRIGGER TX_ARTICULO_VENTA ON DETALLES
	FOR INSERT 
AS
BEGIN
	DECLARE @CANTIDAD INT = (SELECT CANTIDAD FROM inserted)
	DECLARE @IDARTICULO NVARCHAR(5) = (SELECT IDARTICULO FROM inserted)
	DECLARE @STOCK INT = (SELECT STOCK FROM Articulos WHERE
	IdArticulo = @IDARTICULO)

	IF @CANTIDAD > @STOCK 
	BEGIN
		PRINT 'LA CANTIDAD ES MAYOR AL STOCK'
		PRINT 'STOCK : '+ @STOCK
		--CANCELAR LA TRANSACCION
		ROLLBACK 
	END
ELSE
	BEGIN
		PRINT 'TRANSACCION REALIZADA'
		UPDATE Articulos SET Stock = Stock - @CANTIDAD
		WHERE IdArticulo = @IDARTICULO
	END
END
--EN BASE AL EJERCICIO ANTERIOR HACERL O MISMO
--EN LA BASE DE DATOS NORTHWIND - 3
------------------
USE Northwind
SELECT * FROM [ORDER DETAILS]
SELECT * FROM PRODUCTS
GO
INSERT INTO [ORDER DETAILS](ORDERID,PRODUCTID,UNITPRICE,QUANTITY, DISCOUNT)
VALUES(10249,11,14.00,2,0)
CREATE TRIGGER TX_PRODUCTS_VENTA ON [ORDER DETAILS]
	FOR INSERT 
AS
BEGIN
	DECLARE @CANTIDAD INT = (SELECT QUANTITY FROM inserted)
	DECLARE @PRODUCTID NVARCHAR(5) = (SELECT PRODUCTID FROM inserted)
	DECLARE @STOCK INT = (SELECT UNITSINSTOCK FROM PRODUCTS WHERE
	PRODUCTID = @PRODUCTID)

	IF @CANTIDAD > @STOCK 
	BEGIN
		PRINT 'LA CANTIDAD ES MAYOR AL STOCK'
		PRINT 'STOCK : '+ @STOCK
		--CANCELAR LA TRANSACCION
		ROLLBACK 
	END
ELSE
	BEGIN
		PRINT 'TRANSACCION REALIZADA'
		UPDATE PRODUCTS SET UNITSINSTOCK = UNITSINSTOCK - @CANTIDAD
		WHERE PRODUCTID = @PRODUCTID
	END
END

----------------------------------