-- SQL PIVOT - UNPIVOT
/*SQL PIVOT SIRVE PARA REALIZAR TRANSFORMACIONES
DE DATOS (EN LA ESTRUCTURA) / DONDE VA A CAMBIAR
UN CONJUNTO DE DATOS EN COLUMNAS - CAMPOS*/
-- SQL PIVOT - VIENE A SER COMO TABLAS DINÁMICAS EN EXCEL
--(consulta de referencia cruzada)
USE PCVENTAS
GO

CREATE VIEW V_REPORTE_ARTICULOxVENTAxCATEGORIA
AS
SELECT C.Nombre,A.NomArticulo ,D.CANTIDAD 
FROM Categorias C
INNER JOIN Articulos A
ON C.Categoria = A.Categ
INNER JOIN Detalles D
ON A.IdArticulo = D.IdArticulo
--
SELECT nomarticulo, componentes  FROM  V_REPORTE_ARTICULOxVENTAxCATEGORIA
PIVOT (
SUM(CANTIDAD) FOR NOMBRE IN([Componentes],[Multimedias],[Mainboards])
) AS P

