-- VISTAS
---ES UN OBJETO QUE GUARDA UNA CONSULTA
CREATE VIEW V_ARTICULOS_MULTIMEDIA
AS
	SELECT * FROM Articulos A
	INNER JOIN Categorias C
	ON A.Categ = C.cod_categoria
	WHERE C.Nombre LIKE 'MULTIMEDIAS'
	--
SELECT * FROM V_ARTICULOS_MULTIMEDIA
GO
-------------------------
CREATE VIEW V_CATEGORIAS_ARTICULOS
AS
SELECT * FROM Articulos A
	INNER JOIN Categorias C
	ON A.Categ = C.cod_categoria

SELECT * FROM V_CATEGORIAS_ARTICULOS V
INNER JOIN Detalles D ON
V.IDARTICULO = D.IDARTICULO

